import test from 'node:test';
import assert from 'node:assert/strict';
import { fetchRepositoryStatus, compareBaseline } from '../services/githubStatus.js';
const sha = 'a'.repeat(40);
const config = { owner: 'team', repo: 'service', site: 'Service' };
const commit = { sha, html_url: 'https://github.com/team/service/commit/' + sha, author: null, commit: { message: 'Fix telemetry\n\nDetails', author: { name: 'Developer', date: '2026-10-05T00:00:00Z' } } };
function client(runs = []) { return { repos: { get: async () => ({ data: { default_branch: 'main' } }), listCommits: async args => { assert.equal(args.sha, 'main'); return { data: [commit] }; } }, actions: { listWorkflowRunsForRepo: async args => { assert.equal(args.head_sha, sha); return { data: { total_count: runs.length, workflow_runs: runs } }; } } }; }
const run = (id, conclusion, extra = {}) => ({ id, workflow_id: id, head_sha: sha, head_branch: 'main', created_at: '2026-10-05T00:00:00Z', name: 'CI', status: 'completed', conclusion, html_url: 'https://github.com/team/service/actions/runs/' + id, ...extra });
test('shows author without a linked GitHub account and preserves subject', async () => { const data = await fetchRepositoryStatus(client(), config); assert.equal(data.author, 'Developer'); assert.equal(data.latestCommitMessage, 'Fix telemetry'); assert.equal(data.build.state, 'none'); assert.equal(data.branch, 'main'); });
test('Actions access failure preserves commits', async () => { const api = client(); api.actions.listWorkflowRunsForRepo = async () => { throw new Error('forbidden'); }; const data = await fetchRepositoryStatus(api, config); assert.equal(data.githubState, 'available'); assert.equal(data.build.state, 'unavailable'); });
test('failed workflow cannot be hidden by another passing workflow', async () => { const data = await fetchRepositoryStatus(client([run(1, 'success'), run(2, 'failure')]), config); assert.equal(data.build.state, 'failed'); });
test('old commit builds are excluded', async () => { const data = await fetchRepositoryStatus(client([run(1, 'success', { head_sha: 'b'.repeat(40) })]), config); assert.equal(data.build.state, 'none'); });
test('newer rerun supersedes old result', async () => { const data = await fetchRepositoryStatus(client([run(2, 'success', { workflow_id: 1, created_at: '2026-10-06T00:00:00Z' }), run(1, 'failure')]), config); assert.equal(data.build.state, 'passed'); });
test('running and cancelled builds have distinct states', async () => { assert.equal((await fetchRepositoryStatus(client([run(1, null, { status: 'queued' })]), config)).build.state, 'running'); assert.equal((await fetchRepositoryStatus(client([run(1, 'cancelled')]), config)).build.state, 'other'); });
test('repository failure and missing baseline are unknown, not pending', async () => { const api = client(); api.repos.get = async () => { throw new Error('missing'); }; const data = await fetchRepositoryStatus(api, config); assert.equal(data.githubState, 'unavailable'); assert.equal(compareBaseline(data, { service: sha }).status, 'unknown'); assert.equal(compareBaseline({ repo: 'service', latestCommitSha: sha }, {}).status, 'unknown'); });
test('comparison explicitly represents configured baseline', () => { assert.equal(compareBaseline({ repo: 'service', latestCommitSha: sha }, { service: sha }).status, 'up-to-date'); const data = compareBaseline({ repo: 'service', latestCommitSha: sha }, { service: 'b'.repeat(40) }); assert.equal(data.status, 'pending'); assert.equal(data.comparisonSource, 'configured-baseline'); });
